// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
  about: dynamic(() => import("./About")),
  hero: dynamic(() => import("./Hero")),
  reviews: dynamic(() => import("./Reviews")),
  rich_text: dynamic(() => import("./RichText")),
  work: dynamic(() => import("./Work")),
}
