// Code generated by Prismic. DO NOT EDIT.

import About from "./About";
import CodeBlock from "./CodeBlock";
import ExternalLinkCallout from "./ExternalLinkCallout";
import FeaturedProject from "./FeaturedProject";
import Hero from "./Hero";
import ImageContent from "./ImageContent";
import MediaContent from "./MediaContent";
import Notes from "./Notes";
import PageHeading from "./PageHeading";
import Play from "./Play";
import ProjectOverview from "./ProjectOverview";
import ProjectShowcase from "./ProjectShowcase";
import Reviews from "./Reviews";
import RichText from "./RichText";
import TextContent from "./TextContent";
import Work from "./Work";

export const components = {
	about: About,
	code_block: CodeBlock,
	external_link_callout: ExternalLinkCallout,
	featured_project: FeaturedProject,
	hero: Hero,
	image_content: ImageContent,
	media_content: MediaContent,
	notes: Notes,
	page_heading: PageHeading,
	play: Play,
	project_overview: ProjectOverview,
	project_showcase: ProjectShowcase,
	reviews: Reviews,
	rich_text: RichText,
	text_content: TextContent,
	work: Work
};